// <auto-generated />
namespace _60321_2_Severina.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nick : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nick));
        
        string IMigrationMetadata.Id
        {
            get { return "201712061227554_Nick"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
